/*
389. Find the Difference
Easy

1795

344

Add to List

Share
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

func findTheDifference(s string, t string) byte {
	result := 0
	n := len(s)
	for i := 0; i < n; i++ {
		result += int(s[i])
	}
	for i := 0; i < n+1; i++ {
		result -= int(t[i])
	}
	if result < 0 {
		result *= -1
	}
	return byte(result)
}